name: Python Application CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run database tests
      run: |
        python test_database.py
    
    - name: Run application tests
      run: |
        python test_app.py
    
    - name: Test Flask application startup
      run: |
        python -c "from app import app; print('Flask app imports successfully')"
    
    - name: Test database connection
      run: |
        python -c "from DAL import getAllProjects; projects = getAllProjects(); print(f'Database has {len(projects)} projects')"
