name: Python Application CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create database for testing
      run: |
        python -c "from DAL import createDatabase; createDatabase()"
    
    - name: Run database tests
      run: |
        python -m unittest test_database.py -v
    
    - name: Run application tests
      run: |
        python -m unittest test_app.py -v
    
    - name: Test Flask application startup
      run: |
        python -c "from app import app; print('Flask app imports successfully')"
    
    - name: Test database connection
      run: |
        python -c "from DAL import getAllProjects; projects = getAllProjects(); print(f'Database has {len(projects)} projects')"
